### ISSUE TITLE
Outstanding tasks?

### ISSUE THREAD

**Issue by jazzido** [neo4j-contrib/neo4j-elasticsearch#1]
Hi,

My project would benefit a lot from this component, so I'd be interested in contributing. Is there a list of outstanding tasks/issues? Do you intend to continue working on this?

**Comment by jazzido** [comment]
I've started building a parser for the proposed syntax for indices/labels/properties specification: https://github.com/jazzido/neo4j-elasticsearch/commit/d06e631e72fdb826462a19532ebc29da57a8fb63

Let me know if you've already started working on this

**Comment by jazzido** [comment]
Closed in fdda160d82453a6a7839f52a4cb89acbaf38e6e0

**Comment by pauleil** [comment]
Hi,
Do you plan on supporting indexing of relationships anytime soon? Asking because ignoring relations between nodes makes indexing a bit pointless (at least in our use case).
Thanks a lot...

**Comment by jazzido** [comment]
Hi @pauleil,

I don't plan to continue working on this project in the near future. However, I'm sure @jexp will be interested in merging your contributions to it. Also, you might be interested in [my fork](https://github.com/jazzido/neo4j-elasticsearch/) which includes a shell command to do the initial import to the Elastic index.

**Comment by pauleil** [comment]
Thanks for responding so promptly! When you say "the initial import", does it include the edges or only the nodes? Also, jexp, are you working on this project, or is it abandoned, at least for now?

**Comment by jazzido** [comment]
> When you say "the initial import", does it include the edges or only the nodes?

Nodes only. I didn't need to index relationships in my use case.

**Comment by pauleil** [comment]
Understood. Do you have any idea as to how complex it would be to implement indexing relations?

**Comment by jazzido** [comment]
Not hard at all. In my fork, the indexing happens in the [`beforeCommit`](https://github.com/jazzido/neo4j-elasticsearch/blob/master/src/main/java/org/neo4j/elasticsearch/ElasticSearchEventHandler.java#L61) method. There is where should add the logic for updating an index of relationships.
