### ISSUE TITLE
Neo4j-elasticsearch with Neo4j 3.0.3 and Maven dependency

### ISSUE THREAD

**Issue by Artgit** [neo4j-contrib/neo4j-elasticsearch#21]
Hi!

Thanks for this awesome project. Right now I'm trying to move out from Neo4j legacy indexing and looking for possibility to use Elasticsearch for this purpose so this is how I have found Neo4j-elasticsearch project.

I have a questions:
1. Does it support Neo4j 3.0.3 ?
2. Is it possible to include this library as Maven dependency ?

Thanks !

**Comment by jexp** [comment]
Von meinem iPhone gesendet

> Am 14.07.2016 um 08:43 schrieb Artgit notifications@github.com:
> 
> Hi!
> 
> Thanks for this awesome project. Right now I'm trying to move out from Neo4j legacy indexing and looking for possibility to use Elasticsearch for this purpose so this is how I have found Neo4j-elasticsearch project.
> 
> I have a questions:
> 
> Does it support Neo4j 3.0.3 ?
> Yes there is a branch
> Is it possible to include this library as Maven dependency ?
> It's currently not deployed to a repo b/c it's meant to be used as plugin. 

You can probably use it via https://jitpack.io
