### ISSUE TITLE
Questions about Configuration

### ISSUE THREAD

**Issue by shaoyih75** [neo4j-contrib/neo4j-elasticsearch#23]
Hello,

My name is Shaoyi. I am using your repository to connect neo4j and elastic search, I think the plugin is really good, which make the sync easy. Now I have a problem, could you please provide me some suggestions about the problem. I do not want to restart neo4j every time, I guess the way to achieve this is to insert the Configuration directly into Neo4j instead of the Config text file. Could you please tell me how to insert the configuration to the Neo4j directly? 
Could you please tell me which part of your code work as "getting data from text file" so that I can change it a little?
I do not write very good English. Thanks for your time and effort.

Sincerely

**Comment by jexp** [comment]
Unfortunately the configuration is currently only read at startup

We would have to add an endpoint to refresh the config which would be a bigger change. Is it really such a big issue? And why do you need to change config frequently?

Von meinem iPhone gesendet

**Comment by shaoyih75** [comment]
Hello,

Jexp. I am a working on a project for Configuration of a tree-like Mathematics Model. The Model might change their configuration (how the node connected) at some time. In order to make sure the data in ElasticSearch always follow the most up to date configuration, we want to sync it between neo4j and elastic search. And we do not want to restart every time, which might bring a breakdown for the service. I am researching on your code and find that "HttpClientConfig getConfigFor(final String hostName)" Read the port number hostName, but I don't know where your code could get the configuration of Properties. Thank you for pointing me out. Your help is greatly appreciated.

Sincerely

**Comment by jexp** [comment]
I think the easiest way for you to do this, is to fork this plugin and add your custom functionality?

On index changes you probably have to trigger a index rebuild in ElasticSearch.
