### ISSUE TITLE
Release .jar files

### ISSUE THREAD

**Issue by cayasso** [neo4j-contrib/neo4j-elasticsearch#29]
Hi, awesome project. Is there any way to get .jar file for this project as a release, same as how you do with APOC, I think this would help a lot specially for people like me that doesn't use Java and have to start by trying to install Maven on Mac :(

Thank you!!!

**Comment by cheerfulstoic** [comment]
This could be a nice CI script so that it's auto-built

**Comment by jexp** [comment]
Here you go for 3.0.x https://github.com/neo4j-contrib/neo4j-elasticsearch/releases/tag/3.0.0

I'll also add 3.1.x

**Comment by cayasso** [comment]
Awesome this will be very helpfull!

Thank you!
