### ISSUE TITLE
Integration test fails with Elasticsearch 5.1

### ISSUE THREAD

**Issue by rremigius** [neo4j-contrib/neo4j-elasticsearch#33]
Running the tests with Elasticsearch 5.1, the ElasticSearchEventHandlerIntegrationTest fails with the following exception in the console:

```
Jan 13, 2017 2:56:15 PM org.neo4j.elasticsearch.ElasticSearchEventHandler afterCommit
WARNING: Error updating ElasticSearch 
io.searchbox.client.config.exception.NoServerConfiguredException: No Server is assigned to client to connect
```

**Comment by santosh-hegde** [comment]
I was facing the same issue. Update the function `getJestClient` as below which solved my problem. 

`
private JestClient getJestClient(final String hostName) throws Throwable {
		JestClientFactory factory = new JestClientFactory();
		factory.setHttpClientConfig( new HttpClientConfig.Builder(hostName).multiThreaded(true).readTimeout(60000).build());
		return factory.getObject();
	}`

Hope it solves your problem as well.

**Comment by barathank** [comment]
I am getting the same error when testing the integration with ElasticSearch 5.1 and indexes are not created. Please advise.

**Comment by santosh-hegde** [comment]
@barathank Have you made changes in the code I specified above?

**Comment by rremigius** [comment]
@santosh-hegde Your update works, thanks!
