### ISSUE TITLE
Cannot find target/dependency 

### ISSUE THREAD

**Issue by taogoldi** [neo4j-contrib/neo4j-elasticsearch#38]
Using this plugin for the first time and I am trying to follow the instructions you provided in your GitHub. And, I cannot find the target/dependency folder. Searched in previous releases as well and nothing. That might be a rookie mistake but I need some guidance regardless please.

Thank you

**Comment by jexp** [comment]
It missed this line

* Run `mvn dependency:copy-dependencies`. Copy the `jar` files in `target/dependency` to your Neo4j instance's
  `plugins` folder

**Comment by jexp** [comment]
Added it to the readme.
