### ISSUE TITLE
New build for neo4j 3.3.0 or 3.4.0?

### ISSUE THREAD

**Issue by JamesS-M** [neo4j-contrib/neo4j-elasticsearch#48]

**Comment by xiaojinwhu** [comment]
I am also waiting for this

**Comment by OhBonsai** [comment]
me too...

**Comment by OhBonsai** [comment]
Hi,  I found [branch 3.3](https://github.com/neo4j-contrib/neo4j-elasticsearch/tree/3.3)  is useful...  I put jar package into neo4j 3.3 plugin folder.  work fine....

**Comment by jexp** [comment]
I put out releases to use.
