### ISSUE TITLE
when is the new build for neo4j 3.5.0??

### ISSUE THREAD

**Issue by ghost** [neo4j-contrib/neo4j-elasticsearch#54]

**Comment by arikan** [comment]
Hi @jexp, we cannot switch to version 3.5+ due to lack of Elasticsearch plugin. 

We did up the version to 3.5.5 and built it `mvn clean package -DskipTests`, but it throws errors related to `TestGraphDatabaseFactory`.

We'd appreciate if this plugin can be updated as soon as possible.

**Comment by jexp** [comment]
Here you go:

https://github.com/neo4j-contrib/neo4j-elasticsearch/releases/tag/3.5.6
